In [4]:
import os
import pandas as pd

In [140]:
# Merge the signature files - upsig, downsig, and sig
folder_path = "../Volcano_sig/"

def preprocess(group):
    csv_files = [file for file in os.listdir(folder_path) if file.endswith(f"_{group}sig.csv")]

    dfs = []
    for file in csv_files:
        df = pd.read_csv(os.path.join(folder_path, file), header=None)
        if df.shape[1] == 9:
            df = df.iloc[:, 1:]
        dfs.append(df)

    merged_df = pd.concat(dfs, ignore_index=True)
    merged_df = merged_df.rename(columns=merged_df.iloc[0])
    merged_df = merged_df[1:]

    merged_df.dropna(how='all', inplace=True)
    merged_df = merged_df[merged_df['Gene names'] != 'unkown'].reset_index(drop=True)

    # Select rows with padj < 0.1
    merged_df['padj'] = pd.to_numeric(merged_df['padj'], errors='coerce').dropna()
    merged_df = merged_df[merged_df['padj'] < 0.1].reset_index(drop=True)
    # return merged_df.head()

    # For common gene names, keep only that gene which have lower padj
    sorted_df = merged_df.sort_values(by='padj', ascending=True)
    final_df = sorted_df.drop_duplicates(subset='Gene names', keep='first').reset_index(drop=True)
    final_df.to_csv(folder_path + f'merged_{group}sig.csv', index=False)
    return final_df.head()

In [111]:
group = 'up'
print(f"_{group}sig.csv")

_upsig.csv

In [141]:
# preprocess('up')
# preprocess('down')
preprocess('')

,ENSEMBL ID,Gene names,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSRNOG00000003259,C1qtnf1,971.5327586,5.507036853,0.097672895,56.38244704,0,0.0
1,ENSRNOG00000014030,Synm,813.8761217,4.862897706,0.109039125,44.59773215,0,0.0
2,ENSRNOG00000056135,Tsc22d3,7421.822271,4.166756105,0.052765185,78.96790417,0,0.0
3,ENSRNOG00000056153,Tent5b,965.6281874,5.323521085,0.10757162,49.48815562,0,0.0
4,ENSRNOG00000057713,Cav2,2234.732351,2.451718574,0.050287633,48.7539073,0,0.0

In [107]:
# Merge the signature files - upsig, downsig, and sig
folder_path = "../Volcano_sig/"

csv_files = [file for file in os.listdir(folder_path) if file.endswith("upsig.csv")]

dfs = []
for file in csv_files:
    df = pd.read_csv(os.path.join(folder_path, file), header=None)
    if df.shape[1] == 9:
        df = df.iloc[:, 1:]
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)
merged_df = merged_df.rename(columns=merged_df.iloc[0])
merged_df = merged_df[1:]

merged_df.dropna(how='all', inplace=True)
merged_df = merged_df[merged_df['Gene names'] != 'unkown'].reset_index(drop=True).iloc[:, :-1]
print(merged_df.shape)
merged_df.head()

(7146, 8)

,Gene names,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,NaN
0,Cmklr1,1565.34994,3.300235052,0.073543399,44.87466029,0,0.0,NaN
1,ENSRNOG00000015505,Mfap5,4309.548805,2.770010421,0.063649612,43.51967471,0.0,0.0
2,ENSRNOG00000015880,Dpep1,913.9645792,6.224471074,0.128376994,48.48587654,0.0,0.0
3,ENSRNOG00000015904,Wfdc1,2847.047061,2.070765053,0.051844675,39.94171168,0.0,0.0
4,ENSRNOG00000016021,Lims2,1474.010362,3.104012812,0.064358283,48.23019939,0.0,0.0

In [53]:
# Select rows with padj < 0.1
merged_df['padj'] = pd.to_numeric(merged_df['padj'], errors='coerce').dropna()
merged_df = merged_df[merged_df['padj'] < 0.1].reset_index(drop=True)
merged_df

,ENSEMBL ID,Gene names,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSRNOG00000001295,S100b,105.7232384,-3.425173602,0.208743533,-16.40852558,1.66e-60,4.110000e-58
1,ENSRNOG00000002548,Tnn,7886.529183,-2.032985031,0.079591216,-25.54283167,6.6e-144,1.240000e-140
2,ENSRNOG00000004610,Lum,7.4094046,-3.402795687,1.358152498,-2.505459212,0.01222925,4.180649e-02
3,ENSRNOG00000007057,Csmd2,11.75956704,-3.821435752,1.297475289,-2.945285961,0.003226563,1.385703e-02
4,ENSRNOG00000007765,Frzb,17.77693969,-3.113430242,0.551118964,-5.649288895,1.61e-08,2.110000e-07
...,...,...,...,...,...,...,...,...
6199,ENSRNOG00000060703,Troap,421.1356794,3.129617815,0.138451157,22.60449012,3.91e-113,1.970000e-111
6200,ENSRNOG00000060867,Rln1,4.067677709,3.348932486,1.480203157,2.262481653,0.023667661,4.617781e-02
6201,ENSRNOG00000061085,Fancd2,593.2290656,2.54031429,0.111592597,22.76418291,1.04e-114,5.350000e-113
6202,ENSRNOG00000062002,Kcna3,2.137664014,4.355192511,1.703063313,2.557269879,0.010549733,2.222659e-02
6203,ENSRNOG00000062220,Cenpp,81.18777522,2.014171817,0.254101238,7.926650935,2.25e-15,1.480000e-14

In [56]:
# For common gene names, keep only that gene which have lower padj
sorted_df = merged_df.sort_values(by='padj', ascending=True)
final_df = sorted_df.drop_duplicates(subset='Gene names', keep='first').reset_index(drop=True)
final_df

,ENSEMBL ID,Gene names,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSRNOG00000004854,Has2,2875.628839,-3.346042116,0.06225496,-53.74739763,0,0.000000
1,ENSRNOG00000011971,C1s,1413.693676,2.502279555,0.061594709,40.62491067,0,0.000000
2,ENSRNOG00000021919,Rhoj,3706.352936,2.289939764,0.043349902,52.82456616,0,0.000000
3,ENSRNOG00000021840,Cped1,582.6625077,3.421606927,0.086987554,39.33444215,0,0.000000
4,ENSRNOG00000012183,Glrx,6080.453761,6.523988171,0.059576694,109.5057107,0,0.000000
...,...,...,...,...,...,...,...,...
2867,ENSRNOG00000045998,Sema6b,4.758352134,2.340728289,1.048402062,2.232662806,0.025571189,0.049485
2868,ENSRNOG00000055700,Mro,1.689815636,-3.64097488,1.629888119,-2.233880251,0.025490953,0.049522
2869,ENSRNOG00000020733,Kpna5,1.619779366,3.672174007,1.64409934,2.233547522,0.02551286,0.049554
2870,ENSRNOG00000026705,Dgki,1.912416074,3.731017721,1.69825344,2.196973451,0.028022342,0.049691
2871,ENSRNOG00000000708,Sgsm1,1.466937776,-3.815729852,1.737486419,-2.196120677,0.028083307,0.049790

In [59]:
len(final_df['Gene names'].unique())

2872

In [57]:
# Save the datframe
final_df.to_csv(folder_path + 'all_merged_sig.csv', index=False)